package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;
import straten.bo.Gemeente;
import straten.bo.Sector;
import straten.bo.Stadsdeel;
import straten.bo.Wijk;
import straten.bo.Straat;
import straten.dummy.DummyGemeente;
import straten.xml.XMLGemeente;
import straten.xml.XMLGemeente2;

/**
 *
 * @author tiwi 2019
 */
public class gui extends javax.swing.JFrame {

    private final Gemeente gemeente;

    public gui() {
        initComponents();

        initialiseerTabelSectoren();

        //read all data from xml file
        gemeente = new XMLGemeente2("stratenInGent.xml");

        vulStadsdelen();

        cmbStadsdelen.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                vulWijken();
            }
        });

        cmbWijken.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                vulStraten();
            }
        });
    }

    private void vulStadsdelen() {
        cmbStadsdelen.removeAllItems();
        for (Stadsdeel stadsdeel : gemeente.getStadsdelen()) {
            cmbStadsdelen.addItem(stadsdeel);
        }
        cmbStadsdelen.setSelectedIndex(0);
        vulWijken();
    }

    private void vulWijken() {
        cmbWijken.removeAllItems();
        Stadsdeel stadsdeel = (Stadsdeel) cmbStadsdelen.getSelectedItem();
        for (Wijk wijk : stadsdeel.getWijken()) {
            cmbWijken.addItem(wijk);
        }
        cmbWijken.setSelectedIndex(0);
        vulStraten();
    }

    private void vulStraten() {
        Wijk wijk = (Wijk) cmbWijken.getSelectedItem();
        if (wijk == null) {
            lstStraten.setListData(new Straat[0]);
            // hier loopt het soms fout...
        } else {
            lstStraten.setListData(wijk.getStraten().toArray(new Straat[0]));
            lstStraten.setSelectedIndex(0);
            vulSectoren();
        }
    }

    private void vulSectoren() {
        ((DefaultTableModel) tblSectoren.getModel()).setRowCount(0);
        Straat straat = lstStraten.getSelectedValue();
        int i = 0;
        for (Sector sector : straat.getSectoren()) {
            ((DefaultTableModel) tblSectoren.getModel()).addRow(new Object[]{sector.getNaam(), sector.getPaar(), sector.getOnpaar()});
            i++;
        }
    }

    private void initialiseerTabelSectoren() {
        tblSectoren.getColumnModel().removeColumn(tblSectoren.getColumnModel().getColumn(3));
        tblSectoren.getTableHeader().getColumnModel().getColumn(0).setHeaderValue("Naam");
        tblSectoren.getTableHeader().getColumnModel().getColumn(1).setHeaderValue("Paar");
        tblSectoren.getTableHeader().getColumnModel().getColumn(2).setHeaderValue("Onpaar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbStadsdelen = new javax.swing.JComboBox<>();
        cmbWijken = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstStraten = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSectoren = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Stadsdeel");

        jLabel2.setText("Wijk");

        jLabel4.setText("Straten");

        jLabel5.setText("Sectoren");

        cmbStadsdelen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbStadsdelenMouseClicked(evt);
            }
        });

        cmbWijken.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbWijkenMouseClicked(evt);
            }
        });

        lstStraten.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstStratenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstStraten);

        tblSectoren.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblSectoren);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbWijken, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbStadsdelen, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(cmbStadsdelen, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbWijken, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbStadsdelenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbStadsdelenMouseClicked
        vulWijken();
    }//GEN-LAST:event_cmbStadsdelenMouseClicked

    private void cmbWijkenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbWijkenMouseClicked
        vulStraten();
    }//GEN-LAST:event_cmbWijkenMouseClicked

    private void lstStratenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstStratenMouseClicked
        vulSectoren();
    }//GEN-LAST:event_lstStratenMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Stadsdeel> cmbStadsdelen;
    private javax.swing.JComboBox<Wijk> cmbWijken;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<Straat> lstStraten;
    private javax.swing.JTable tblSectoren;
    // End of variables declaration//GEN-END:variables
}
